//ERROR_TYPES.md provides documentations
exports.errorTypes = {
  AuthenticationError: "AuthenticationError",
  AuthenticationTimeoutError: "AuthenticationTimeoutError",
  AuthorizationError: "AuthorizationError",
  BadRequestError: "BadRequestError",
  ConflictError: "ConflictError",
  ConfigurationError: "ConfigurationError",
  DataIntegrityError: "DataIntegrityError",
  DatabaseConnectionError: "DatabaseConnectionError",
  DependencyError: "DependencyError",
  ExternalAPIError: "ExternalAPIError",
  FileSystemError: "FileSystemError",
  LengthRequiredError: "LengthRequiredError",
  MethodNotAllowedError: "MethodNotAllowedError",
  NotFoundError: "NotFoundError",
  NotAcceptableError: "NotAcceptableError",
  PayloadTooLargeError: "PayloadTooLargeError",
  PermissionDeniedError: "PermissionDeniedError",
  PreconditionFailedError: "PreconditionFailedError",
  RateLimitError: "RateLimitError",
  RequestTimeoutError: "RequestTimeoutError",
  ResourceExhaustedError: "ResourceExhaustedError",
  ServerError: "ServerError",
  ServiceUnavailableError: "ServiceUnavailableError",
  TimeoutError: "TimeoutError",
  TooManyRequestsError: "TooManyRequestsError",
  URITooLongError: "URITooLongError",
  UnsupportedHTTPVersionError: "UnsupportedHTTPVersionError",
  UnsupportedMediaTypeError: "UnsupportedMediaTypeError",
  UpgradeRequiredError: "UpgradeRequiredError",
  ValidationError: "ValidationError",
};
